(include_subdirs qualified)

; The application is a library so it compiles once and tests can link it; the
; executables only pick a backend.

(library
 (name messenger_test)
 (modules
  (:standard \ main main_desktop))
 (libraries ml-messenger)
 (flags
  (:standard -warn-error -A)))

(executable
 (name main)
 (modules main)
 (libraries regl_js messenger_test)
 (modes js)
 (flags
  (:standard -warn-error -A)))

(executable
 (name main_desktop)
 (modules main_desktop)
 (libraries regl_desktop messenger_test)
 (modes
  (native exe))
 (flags
  (:standard -warn-error -A)))

(rule
 (target main_desktop.ml)
 (deps main.ml)
 (action
  (copy %{deps} %{target})))
